Fixing issues with disconnections

diff --git a/migrate b/migrate
--- a/migrate
+++ b/migrate
@@ -1,46 +1,46 @@
 #!/bin/bash
 
-if [ "$#" -ne 3 ]; then
+if [ "$#" -ne 10 ]; then
     echo "Illegal number of parameters"
     exit 1
 fi
 
-####### Project name
-PROJECT_NAME=$1
-#EMAIL="wellsky.com"
-
 ###########################
 ####### SVN
 # SVN repository to be migrated
-USERNAME=$2
-PASSWORD=$3
-BASE_SVN="https://svn.bowmansystems.local/$PROJECT_NAME"
-SVN_ARGS=" --non-interactive --username=$USERNAME --password=$PASSWORD"
+SVN_HOST=$1
+SVN_USER=$2
+SVN_PASSWORD=$3
+SVN_BRANCHES=$4
+SVN_TAGS=$5
+SVN_TRUNK=$6
 
-# Organization inside BASE_SVN
-BRANCHES="branches"
-TAGS="tags"
-TRUNK="trunk"
+GIT_HOST=$7
+GIT_USER=$8
+GIT_PASSWORD=$9
+
+####### Project name #######
+PROJECT_NAME=$10
+
+BASE_SVN="$SVN_HOST/$PROJECT_NAME"
+SVN_ARGS=" --non-interactive --username=$SVN_USER --password=$SVN_PASSWORD"
+
+####### Removes slashes from the project name and replace it with underscore
+PROJECT_NAME=${PROJECT_NAME//[\/]/_}
 
 ###########################
 ####### GIT
 # Git repository to migrate
-GIT_URL="https://10.3.4.190/jcastrillon/${PROJECT_NAME}_test.git"
-
-###########################
-#### Don't need to change from here
-###########################
+GIT_URL="$GIT_HOST/$GIT_USER/${PROJECT_NAME}.git"
 
 # Geral Configuration
 ABSOLUTE_PATH=$(pwd)
 TMP=$ABSOLUTE_PATH/"migration-"$PROJECT_NAME
 
 # Branchs Configuration
-SVN_BRANCHES=$BASE_SVN/$BRANCHES
-SVN_TAGS=$BASE_SVN/$TAGS
-SVN_TRUNK=$BASE_SVN/$TRUNK
-
-AUTHORS=$TMP/$PROJECT_NAME"-authors.txt"
+SVN_BRANCHES=$BASE_SVN/$SVN_BRANCHES
+SVN_TAGS=$BASE_SVN/$SVN_TAGS
+SVN_TRUNK=$BASE_SVN/$SVN_TRUNK
 
 echo '[LOG] Starting migration of '$SVN_TRUNK
 echo '[LOG] Using: '$(git --version)
@@ -56,13 +56,6 @@ cd $TMP
 echo
 echo '[LOG] Getting SSL certificates'
 svn info $BASE_SVN $SVN_ARGS
-
-#echo
-#echo '[LOG] Checking the authors file'
-if [ ! -f $AUTHORS ]; then
-    echo "Authors file not found!"
-    exit 1
-fi
 
 echo
 echo '[LOG] Getting first revision'
@@ -96,17 +89,28 @@ do
   git branch -rd $ref
 done
 
-# echo
-# echo '[RUN] git push'
-# git branch –r
-# git svn show-ignore > .gitignore
-# git config --global http.sslVerify false
-# cp -rf .git/refs/remotes/origin/tags/* .git/refs/tags/
-# rm -rf .git/refs/remotes/origin/tags
-# cp -rf .git/refs/remotes/origin/* .git/refs/heads/
-# rm -rf .git/refs/remotes/origin
-# git branch -d trunk
-# git push origin --all
-# git push origin --tags
 
-echo 'Sucessufull.'
+push() {
+    git branch –r
+    git svn show-ignore > .gitignore
+    git config --global http.sslVerify false
+    cp -rf .git/refs/remotes/origin/tags/* .git/refs/tags/
+    rm -rf .git/refs/remotes/origin/tags
+    cp -rf .git/refs/remotes/origin/* .git/refs/heads/
+    rm -rf .git/refs/remotes/origin
+    git branch -d trunk
+    git push origin --all
+    git push origin --tags
+
+    OUTPUT=$?
+}
+echo
+echo '[RUN] git push'
+
+# Call the function to push
+push
+if [[ $OUTPUT -eq 0 ]]; then
+    echo 'Sucessufull.'
+else
+    echo 'Error!'
+fi
